package com.roms.enums;

public enum CandidateStatus {
    APPLIED,
    DOCUMENTS_PENDING,
    DOCUMENTS_UNDER_REVIEW,
    DOCUMENTS_APPROVED,
    INTERVIEW_SCHEDULED,
    INTERVIEW_COMPLETED,
    MEDICAL_IN_PROGRESS,
    MEDICAL_PASSED,
    OFFER_ISSUED,
    OFFER_SIGNED,
    DEPLOYED,
    PLACED,
    REJECTED,
    WITHDRAWN
}
