package com.roms.enums;

public enum CandidateStatus {
    APPLICATION_SUBMITTED,
    UNDER_REVIEW,
    DOCUMENTS_INSUFFICIENT,
    DOCUMENTS_APPROVED,
    INTERVIEW_SCHEDULED,
    INTERVIEW_PASSED,
    MEDICAL_PENDING,
    MEDICAL_PASSED,
    VISA_PROCESSING,
    OFFER_ISSUED,
    OFFER_ACCEPTED,
    DEPLOYMENT_PENDING,
    PLACED,
    REJECTED
}
